---

- name: Get current timezone from the host
  slurp:
    src: '/etc/timezone'
  register: php__etc_timezone

- name: "Add Ondřej Surý PPA key"
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: 4F4EA0AAE5267A6C
    state: present
  when: ansible_distribution_release == 'xenial' and php__version == '5.6'
  tags: [ provision ]

- name: "Add Ondřej Surý PPA repository"
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present
    update_cache: yes
  when: ansible_distribution_release == 'xenial' and php__version == '5.6'
  tags: [ provision ]

- name: Make sure PHP-FPM support is installed
  apt:
    pkg: 'php{{ php__version }}-{{ item }}'
    state: 'latest'
    install_recommends: no
  with_items: [ 'fpm', 'cli' ]
  tags: [ provision ]

- name: Make sure that Ansible local facts directory is present
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  tags: [ provision ]

- name: Save PHP-FPM local facts
  template:
    src: 'etc/ansible/facts.d/php.fact.j2'
    dest: '/etc/ansible/facts.d/php.fact'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: php_register_local_facts
  tags: [ provision ]

- name: Gather facts if they were modified
  action: setup
  when: php_register_local_facts.changed
  tags: [ provision ]

- name: Install PHP packages
  apt:
    pkg: "{{ item|search('php.*-')|ternary(item, 'php' + php__version + '-' + item) }}"
    state: 'latest'
    install_recommends: no
  with_flattened:
    - '{{ php__packages }}'
    - '{{ php__base_packages }}'
    - '{{ php__group_packages }}'
    - '{{ php__host_packages }}'
  notify: ['Restart php-fpm']
  tags: [ provision ]

- name: "Create directory for php*-fpm logs"
  file:
    path: '/var/log/php{{ php__version }}-fpm'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0700'

- name: "Check existence of php-fpm-reopenlogs"
  stat:
    path: '{{ php__lib_base }}/php{{ php__version }}-fpm-reopenlogs'
  register: php__register_reopenlogs

- name: "Configure logrotate for php-fpm"
  template:
    src: 'etc/logrotate.d/php-fpm.j2'
    dest: '/etc/logrotate.d/php{{ php__version }}-fpm'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: "Create directory for php/fpm under etc"
  file:
    path: '{{ php__etc_base }}/fpm'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: "Configure php.ini for php-fpm"
  template:
    src: 'etc/php/php.ini.j2'
    dest: '{{ php__etc_base }}/fpm/php.ini'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: "Restart php-fpm"

- name: "Create directory for php/cli under etc"
  file:
    path: '{{ php__etc_base }}/cli'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: "Configure php.ini for CLI"
  template:
    src: 'etc/php/php.ini.j2'
    dest: '{{ php__etc_base }}/cli/php.ini'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Check if pool-available.d/ directory exists
  stat:
    path: '{{ php__etc_base }}/fpm/pool-available.d'
  register: pool_available_d

- name: "Remove default php-fpm pool if exists"
  file:
    path: '{{ php__etc_base }}/fpm/pool.d/www.conf'
    state: absent
  when: not pool_available_d.stat.exists

- name: "Create pool-available.d/ directory for php-fpm"
  file:
    path: '{{ php__etc_base }}/fpm/pool-available.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: "Ensure pool.d/ directory for php*-fpm exists"
  # Just for the case it has been deleted manually
  file:
    path: '{{ php__etc_base }}/fpm/pool.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- include: php_pools.yml
  when: php__manage_pools|default(True)|bool

- meta: flush_handlers
  when: not php__in_container|d(False)|bool

- name: Test if using a phusion image
  stat:
    path: "/sbin/my_init"
  register: php__my_init_output
  when: php__in_container|d(False)|bool

- name: Make sure /etc/service/php-fpm exists
  file:
    path: /etc/service/php-fpm
    state: directory
  when: php__in_container|d(False)|bool and php__my_init_output.stat.exists

- name: Install php-fpm at boot
  template:
    src: etc/service/php-fpm-init.sh
    dest: /etc/service/php-fpm/run
    mode: "a+x"
  when: php__in_container|d(False)|bool and php__my_init_output.stat.exists
